### PR TITLE
[sdk-foreach] Initial commit. Contribute to JB#36492

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Comment by jlehtoranta** [comment]
Excellent, but how about excluding hardware devices by default and having them included only by a separate option?

**Comment by martyone** [comment]
Originally I planned to add (more) options like that but soon I become afraid such a feature would hardly find some users - who deals with more than three devices? :) The -i (interactive) option works well here, don't you think?

**Comment by jlehtoranta** [comment]
Ok, I think the default mode should be the interactive mode then - just to be safe that only users, who intend to run the same command on *all* devices, do it.

**Comment by jlehtoranta** [comment]
lgtm now 👍

**Pull request merged**
